import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TARGET_FILE = path.join(__dirname, '../data/tw_stocks.ts');

// Helper to wait
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchTWSE() {
    console.log('Fetching TWSE (Listed) stocks...');
    try {
        const response = await fetch('https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL');
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        // data structure: array of { Code, Name, ... }
        return data.map(item => ({
            code: item.Code,
            name: item.Name
        }));
    } catch (error) {
        console.error('Error fetching TWSE:', error);
        return [];
    }
}

async function fetchTPEX() {
    console.log('Fetching TPEX (OTC) stocks...');
    try {
        // TPEX Open API for daily quotes
        const response = await fetch('https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes');
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        // data structure: array of { Code, Name, ... }
        return data.map(item => ({
            code: item.Code,
            name: item.Name
        }));
    } catch (error) {
        console.error('Error fetching TPEX:', error);
        return [];
    }
}

// Function to extract existing aliases from the file content
function extractAliases(fileContent) {
    const aliasMap = new Map();
    // Regex to find object literals with aliases
    // Looks for: { code: '1234', name: '...', alias: [...] }
    const regex = /\{[^}]*code:\s*'([^']+)'[^}]*alias:\s*(\[[^\]]+\])[^}]*\}/g;

    let match;
    while ((match = regex.exec(fileContent)) !== null) {
        const code = match[1];
        const aliasStr = match[2];
        try {
            // Evaluates the array string safely-ish by JSON parsing if we replace ' with "
            // But since it's JS array literal, might have single quotes.
            // Let's just store the raw string and re-inject it, or better:
            // Remove quotes and split.
            const cleaned = aliasStr.replace(/[\[\]'"]/g, '').split(' , ').map(s => s.trim()).filter(s => s);

            // Actually, we can just grab the array content literal to make it easier to write back
            // But to be safe, let's parse it properly.
            // Simplified approach: just strictly parse single quoted strings
            const aliases = aliasStr.match(/'([^']+)'/g)?.map(s => s.replace(/'/g, '')) || [];
            if (aliases.length > 0) {
                aliasMap.set(code, aliases);
            }
        } catch (e) {
            console.warn(`Failed to parse alias for ${code}`);
        }
    }
    return aliasMap;
}

async function main() {
    // 1. Read existing file to preserve aliases
    let existingContent = '';
    const aliases = new Map();

    if (fs.existsSync(TARGET_FILE)) {
        console.log('Reading existing file to preserve aliases...');
        existingContent = fs.readFileSync(TARGET_FILE, 'utf-8');
        const extracted = extractAliases(existingContent);
        extracted.forEach((v, k) => aliases.set(k, v));
        console.log(`Preserved aliases for ${aliases.size} stocks.`);
    }

    // 2. Fetch new data
    const twseStocks = await fetchTWSE();
    const tpexStocks = await fetchTPEX();

    // 3. Merge and deduplicate
    const allStocks = [...twseStocks, ...tpexStocks];
    // Map to remove duplicates, prioritize TWSE if overlap (unlikely)
    const stockMap = new Map();
    allStocks.forEach(stock => {
        stockMap.set(stock.code, stock.name);
    });

    // 4. Sort by code
    const sortedCodes = Array.from(stockMap.keys()).sort();

    // 5. Generate new content
    const newStockObjects = sortedCodes.map(code => {
        const name = stockMap.get(code);
        const stockAliases = aliases.get(code);

        let objStr = `  { code: '${code}', name: '${name}'`;
        if (stockAliases && stockAliases.length > 0) {
            const aliasContent = stockAliases.map(a => `'${a}'`).join(', ');
            objStr += `, alias: [${aliasContent}]`;
        }
        objStr += ' }';
        return objStr;
    });

    const fileContent = `// A comprehensive list of Taiwan stocks (TSE, OTC) and ETFs.
// This list is auto-generated by scripts/update-stocks.js.
// Last Updated: ${new Date().toISOString().split('T')[0]}

export const TW_STOCKS: { code: string; name: string; alias?: string[] }[] = [
${newStockObjects.join(',\n')}
];
`;

    // 6. Write back
    fs.writeFileSync(TARGET_FILE, fileContent, 'utf-8');
    console.log(`Successfully updated ${TARGET_FILE} with ${newStockObjects.length} stocks.`);
}

main().catch(console.error);
